### ISSUE TITLE
Medic's Spawn with the wrong toolkit (not the virtual inventory toolkit)

### ISSUE THREAD

**Issue by sync0s** [sync0s/i3t#2]
**Original Reporter**

Slovy

**Original Description:** 

> tool kits (for medics) placed in backpack (i inv) from spawn dont work. they have to buy the virtual inv. toolkit to repair a vehicle. 

**Pertinent Information**

> Plans are to get rid of the virtual items system very soon. Keep this in mind.

**Comment by Slovy** [comment]
possible fix pushed.
