### ISSUE TITLE
Map Issue at the GTOWN med center

### ISSUE THREAD

**Issue by iiTzBang** [sync0s/i3t#33]
the wall and flooring bugged out. 

http://images.akamai.steamusercontent.com/ugc/107355289207879618/B2E6EF598008E8D0F3F2A8E7A9E2A86E4A3BED20/

http://images.akamai.steamusercontent.com/ugc/107355289207879962/6C4AF85BCC92E94241DCEA5B05F8F79165A9839F/

**Comment by paulq813** [comment]
Changed altitude of ground in new HQ area. Tested and fixed.
