### ISSUE TITLE
Something (possibly undermap blocking car shop)

### ISSUE THREAD

**Issue by adammio** [sync0s/i3t#34]
Unsure what created it or how to recreate it, noticed it happening at 03:54am GMT time 11/12/2016 

Gif of what it says and happens: https://gyazo.com/24d61200833a02fa056efa2dfd4ccd7f

Pretty much there is nothing blocking the spawn how ever there is nothing on the spawn point so im thinking something may be stuck under the map? Or it thinks that a car is there when it is not.

Money is not lost since it doesn't actually try to spawn the car due to it being "blocked"

Sorry it wouldn't let me add a Label

**Comment by paulq813** [comment]
Slightly relocated car spawn location
