### ISSUE TITLE
Hospital is lame looking!

### ISSUE THREAD

**Issue by iiTzBang** [sync0s/i3t#58]
Give me the hospital with some cool decor mods now feelgood or i will ddos you IRL in your face with a meat pie filled with hot steaming man chowder PLease

**Comment by sync0s** [comment]
Either Wally didn't walk you through it, or you've already been told. Find the mods yourself, and include them in the changes.txt. (If it's an unreasonable size then you'll need to clear it with me first)

**Comment by sync0s** [comment]
Also, last mod update already added the two hospital beds in

**Comment by iiTzBang** [comment]
gg all i needed to know :)

**Comment by iiTzBang** [comment]
@sync0s someone told me i think wally maybe that the A3L mod had some cool shit in it for the hospital as far as decor goes,,, I'd imagine that is a big mod and I dont know if there is anyway of just takingg what i need out of it. Can you shed some light on this mod???

**Comment by WalgreensSecurity** [comment]
Closing because no reason to have this in the issues as of now
