### ISSUE TITLE
Gas Station Robbery Issue

### ISSUE THREAD

**Issue by iiTzBang** [sync0s/i3t#68]
Gas station robbery not giving money after being robbed in cash or bank account

**Comment by iiTzBang** [comment]
also it says on the screen that you got money but dosnt give it to you. and the dollar amount i got from 3 gas stations was no more than 120 dollars... FeelGood said that it was RNGGG based from 500 to 1500????

**Comment by iiTzBang** [comment]
only problem remaining is you dont get the money after robbing the stations

**Comment by skinner904** [comment]
Getting decent robberies now. $2k-$5k but yes still not actually being deposited into Cash or Bank.

**Comment by paulq813** [comment]
Issue Resolved
