### ISSUE TITLE
EMS Helicopter GARAGE spawn broken, also buying items while inventory is full.

### ISSUE THREAD

**Issue by Talaeyn** [sync0s/i3t#71]
The helicopter shop for ems spawns helicopters fine, but when you take them out of the garage is apparently blows them up. Also when buying items my inventory was full but it did not stop me from being able to buy items, not sure if thats really important though more a common sense thing I suppose. Might be a problem if people are trying to buy more than one gun from rebel or something and it just eats 150K+ money.

**Comment by paulq813** [comment]
Issue Resolved
